name: Build Android CI

on:
  push:
    branches:
      - main
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Get Latest Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run lint